version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolar
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/q.sql"